package resource.enums;

public enum RulesSQL {
    NON_EXISTING_TABLE,
    NON_EXISTING_COLUMN,
    QUERY_NOT_VALID,
    QUERY_WRONG_ORDER,
    ALIAS_DOUBLE_QUOTES,
    FUNCTION_MISSING_GROUP_BY,
    WHERE_WRONG_FUNCTION,
    CSV_FILE_NOT_VALID
}
